#!/usr/bin/env bash
# post_init.sh — runs after /init to update timestamps, structure, and dependency diffs
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$PROJECT_ROOT"

# ──────────────────────────────────────────────
# 1. Update Last Updated timestamp in docs/architecture.md
# ──────────────────────────────────────────────
ARCH_FILE="docs/architecture.md"
TODAY=$(date +%Y-%m-%d)

if [ -f "$ARCH_FILE" ]; then
  sed -i "s/^Last Updated: .*/Last Updated: $TODAY/" "$ARCH_FILE"
  echo "[post_init] Updated timestamp in $ARCH_FILE"
else
  echo "[post_init] WARNING: $ARCH_FILE not found — skipping timestamp update"
fi

# ──────────────────────────────────────────────
# 2. Regenerate docs/structure.md with current file tree
# ──────────────────────────────────────────────
STRUCTURE_FILE="docs/structure.md"

cat > "$STRUCTURE_FILE" << 'HEADER'
# Project Structure

> Auto-generated by `post_init.sh` — do not edit manually.

```
HEADER

# Use find, excluding common noise directories/files
find . \
  -name '.git' -prune -o \
  -name '__pycache__' -prune -o \
  -name 'venv' -prune -o \
  -name '.venv' -prune -o \
  -name '*.pyc' -prune -o \
  -name '.idea' -prune -o \
  -name 'node_modules' -prune -o \
  -print | sort >> "$STRUCTURE_FILE"

echo '```' >> "$STRUCTURE_FILE"
echo "" >> "$STRUCTURE_FILE"
echo "Last generated: $TODAY" >> "$STRUCTURE_FILE"

echo "[post_init] Regenerated $STRUCTURE_FILE"

# ──────────────────────────────────────────────
# 3. Diff dependencies against last snapshot
# ──────────────────────────────────────────────
DECISIONS_DIR="docs/decisions"
SNAPSHOT_FILE="$DECISIONS_DIR/.last_deps_snapshot"
PENDING_FILE="$DECISIONS_DIR/.pending_adr_review"
DEPS_FILE=""

# Detect dependency file
if [ -f "requirements.txt" ]; then
  DEPS_FILE="requirements.txt"
elif [ -f "pyproject.toml" ]; then
  DEPS_FILE="pyproject.toml"
fi

if [ -n "$DEPS_FILE" ]; then
  if [ -f "$SNAPSHOT_FILE" ]; then
    DIFF_OUTPUT=$(diff "$SNAPSHOT_FILE" "$DEPS_FILE" 2>/dev/null || true)
    if [ -n "$DIFF_OUTPUT" ]; then
      echo "# Pending ADR Review" > "$PENDING_FILE"
      echo "" >> "$PENDING_FILE"
      echo "Dependencies changed since last snapshot." >> "$PENDING_FILE"
      echo "Source: \`$DEPS_FILE\`" >> "$PENDING_FILE"
      echo "Detected: $TODAY" >> "$PENDING_FILE"
      echo "" >> "$PENDING_FILE"
      echo '```diff' >> "$PENDING_FILE"
      echo "$DIFF_OUTPUT" >> "$PENDING_FILE"
      echo '```' >> "$PENDING_FILE"
      echo ""
      echo "⚠️  [post_init] Dependency changes detected — wrote diff to $PENDING_FILE"
      echo "   Run /init inside Claude Code to process ADR reviews."
    else
      echo "[post_init] No dependency changes detected."
    fi
  else
    echo "[post_init] No previous snapshot found — creating initial baseline."
  fi

  # Update snapshot
  cp "$DEPS_FILE" "$SNAPSHOT_FILE"
  echo "[post_init] Updated dependency snapshot: $SNAPSHOT_FILE"
else
  echo "[post_init] No requirements.txt or pyproject.toml found — skipping dependency diff."
  # Create empty snapshot so future runs have a baseline
  touch "$SNAPSHOT_FILE"
fi

# ──────────────────────────────────────────────
# 4. Make this script executable (idempotent)
# ──────────────────────────────────────────────
chmod +x "$0"

echo "[post_init] Done."